language: node_js
node_js:
  - "7"

sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/docker-cache/

notifications:
  email: false

env:
  global:
    - COMPONENT=agile-data
    - DOCKER_CACHE_FILE=/home/travis/docker-cache/cache.tar.gz
    - secure: lebGJc1MfEFqBEjJlwmaOCSpL5EXCi5pPt56uD8MdG93sslK3ucQyNBvLmzpdwlcaicjn+ZW6VLVbr8E4qphDKRqEGpFnRGADVk01rudVlsUmaEG3g31aYH0Oayztp6lpKuSTwbRLGuuPK1bP3tqtDCekQ02tq7TI0UJj3rFydU9wcNCSpBXQEUlaPIIvCDz9x1jOi8fKhNigbVV9pdHVc7D7fpI/RjWfOcmmK2Wm/3BZ3AWERNV3HwTFFPfoRq7P8uDbNiJbp7IeTCAVC/jS1tNs2xQAJN6KGJtpiHTp4/t8FFL8HhUKWCsGKytLsiqZX16CtAU2ZSmQg3i3DHy3FtGrY+TO+D6GLazpeeHPxaX99bTAzh6N39iuR6aUIQweXYsN7e3DqMT5eaxONZ90tA/TWJXgbMlC44jZhiaYnTRPZ7OgpihcHH9zd+NuOi2HROYwtwFCKCwLX7/2RYj/iOm5B5rh4dYqNK3NHMHYwfaSPQa2TnOBS/F4c2KbOd4JBtVdAB0TAxgV11vkYi10J5nktagcRrIIOWRnoMi3MN/KLe4QZReriIuKU8wp9BkUjQYsjKrpGefKTqVV4XDtujNDhExKip8NZlXsat0yf9bc9MKuB31wvZcF6pF38RAusZ2d/8iBv1jZNJovKkERzJk2lb96+THvEXpYIqSspU=
    - secure: ZrZUF9IGDm3Jm6DonYYvMCx4CQTv/ZboTXibc98yX2MkpCGw9Osu7Jzg/1+12pgTFMfMn+6rKLj7UHKQgjR5jngKitVFUpEhmVXoQrdwcLMiUENFcmXJKWqK2cna3hm/LSu9fHz1dACT7pwsFjvllrkmtYY/Qrla6eEbE7v0jzOauHj5urNRlxFLoayX15X5hYfBRN0Mqaj7VZ6w/8SqfL0tTz+FcCbSEAfg3CUK/AI0DYcrEZbNGa4we+4faPYD8q0YmOXAlWI1DX3BNFYp7024CyxExwSnJjzY/YczwnaMrCJm94oVeArIX45NF2zbUaQBcszl4acAvL0IhIM5kmcNWSxE39xGetonh7fZQbO4tOu0SaDn2ERPtmIoObY5JQSQ7L62nTzQmem7Rxd5hc2F1Tc1hF3to88m/TSHqVNOPVGyIp4TF9rV5sO/jf4DlU+JBFEs0kWlpzqMOCvodxiR6RCZVBEEw4o75fipzq0Azyc7v7DDxvvmT2X9xn3jq3EohNtI43quA/3rSg/i2wlNN8JU5FeQagE/28ntab7rbDslba8p/atNdEO3drN8CuUU+/851dTzcyuUvg8DUCKuZhf1law8Oo1hYGkqJFTJnNlmHgIfl5eHAmR5syBXk8iCRL8EyvOyI0VXrzy/xTwboTfHJirXUpyU8YUyA3s=
  matrix:
    - DOCKER_IMAGE=agileiot/$COMPONENT-armv7l
      VERSIONIST=true
    - DOCKER_IMAGE=agileiot/$COMPONENT-x86_64
      BASEIMAGE=resin\\/intel-nuc-node:7.8.0-20170506
      ARCH=amd64

before_install:
  - source <(curl -s https://raw.githubusercontent.com/Agile-IoT/agile-ci-scripts/master/before_install.sh)
  - echo "Tagging the build with tag - $DOCKER_TAG"

script:
  - if [[ -n ${DOCKER_TAG} ]]; then
      docker build -t $DOCKER_IMAGE:$DOCKER_TAG .;
      docker run --env NODE_ENV=TEST $DOCKER_IMAGE:$DOCKER_TAG;
    fi

after_success:
  - source <(curl -s https://raw.githubusercontent.com/Agile-IoT/agile-ci-scripts/master/after_success.sh)
