language: node_js

sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/docker-cache/

notifications:
  email: false

env:
  global:
    - COMPONENT=agile-data
    - DOCKER_CACHE_FILE=/home/travis/docker-cache/cache.tar.gz
  matrix:
    - DOCKER_IMAGE=agileiot/$COMPONENT-armv7l
    - DOCKER_IMAGE=agileiot/$COMPONENT-x86_64
      BASEIMAGE=resin\\/intel-nuc-node:7.8.0-20170506
      ARCH=amd64

before_install:
  - if [ "$BASEIMAGE" ] ; then sed -i "s/^FROM .*/FROM $BASEIMAGE/" Dockerfile ; fi
  - if [ "$ARCH" ] ; then sed -i "s/armhf/$ARCH/g" Dockerfile ; fi
before_script:
  - docker run --rm --privileged multiarch/qemu-user-static:register
script:
  - docker build -t agile-data-test -f Dockerfile . && docker run --env NODE_ENV=TEST agile-data-test
node_js:
  - "7"
